/**
 * Tools: sophos_list_ba_quotes, sophos_get_ba_quote,
 *        sophos_get_ba_partner_levels, sophos_get_ba_pricing
 * Interact with the Sophos Business Automation API /business-automation/v1/
 * (global host). Distributor-scoped: every call needs a distributor ID and
 * distributor-entitled API credentials.
 */

import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { SophosClient } from "../client/sophos-client.js";
import type { TenantResolver } from "../client/tenant-resolver.js";
import { jsonResult, withErrorHandling } from "./helpers.js";
import { DEFAULT_PAGE_SIZE } from "../config/config.js";

export function registerBusinessAutomationTools(
  server: McpServer,
  client: SophosClient,
  _tenantResolver: TenantResolver
): void {
  // --- List Quotes ---
  server.registerTool(
    "sophos_list_ba_quotes",
    {
      title: "List Sophos Business Automation Quotes",
      description: `List distributor quotes (new, amendment, renewal).

Requires distributor-entitled API credentials; partner credentials get a
permission error.

Args:
  - distributor_id (string): Distributor ID (X-Distributor-ID).
  - type (string, optional): Quote type: "new", "amendment", "renewal".
  - billing_category_type (string, optional): "upfront" or "nonStandard".
  - autogenerated (boolean, optional): Only autogenerated quotes.
  - created_by_partner (boolean, optional): Only partner-created quotes.
  - expires_within_days (number, optional): Quotes expiring within N days.
  - created_minutes_ago (number, optional): Quotes created in the past N minutes.
  - approved_minutes_ago (number, optional): Quotes approved in the past N minutes.
  - approved_from (string, optional): Quotes approved from this datetime.
  - approved_to (string, optional): Quotes approved up to this datetime.
  - limit (number, optional): Max results per page (default 50).
  - page (number, optional): Page number (default 1).`,
      inputSchema: {
        distributor_id: z.string().uuid().describe("Distributor ID"),
        type: z.enum(["new", "amendment", "renewal"]).optional().describe("Quote type"),
        billing_category_type: z
          .enum(["upfront", "nonStandard"])
          .optional()
          .describe("Quote line billing category type"),
        autogenerated: z.boolean().optional().describe("Only autogenerated quotes"),
        created_by_partner: z
          .boolean()
          .optional()
          .describe("Only partner-created quotes"),
        expires_within_days: z
          .number()
          .int()
          .optional()
          .describe("Quotes expiring within N days"),
        created_minutes_ago: z
          .number()
          .int()
          .optional()
          .describe("Quotes created in the past N minutes"),
        approved_minutes_ago: z
          .number()
          .int()
          .optional()
          .describe("Quotes approved in the past N minutes"),
        approved_from: z
          .string()
          .optional()
          .describe("Quotes approved from this datetime"),
        approved_to: z
          .string()
          .optional()
          .describe("Quotes approved up to this datetime"),
        limit: z
          .number()
          .int()
          .min(1)
          .max(100)
          .optional()
          .default(DEFAULT_PAGE_SIZE)
          .describe("Max results per page (default 50)"),
        page: z
          .number()
          .int()
          .min(1)
          .optional()
          .default(1)
          .describe("Page number (default 1)"),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    withErrorHandling(
      async ({
        distributor_id,
        type,
        billing_category_type,
        autogenerated,
        created_by_partner,
        expires_within_days,
        created_minutes_ago,
        approved_minutes_ago,
        approved_from,
        approved_to,
        limit,
        page,
      }) => {
        const params: Record<string, string> = {
          pageSize: String(limit),
          page: String(page),
        };
        if (type) params.type = type;
        if (billing_category_type) params.billingCategoryType = billing_category_type;
        if (autogenerated !== undefined) params.autogenerated = String(autogenerated);
        if (created_by_partner !== undefined)
          params.createdByPartner = String(created_by_partner);
        if (expires_within_days !== undefined)
          params.expiresWithinDays = String(expires_within_days);
        if (created_minutes_ago !== undefined)
          params.createdMinutesAgo = String(created_minutes_ago);
        if (approved_minutes_ago !== undefined)
          params.approvedMinutesAgo = String(approved_minutes_ago);
        if (approved_from) params.approvedFrom = approved_from;
        if (approved_to) params.approvedTo = approved_to;

        const data = await client.globalRequest<Record<string, unknown>>(
          "/business-automation/v1/quotes",
          { params, headers: { "X-Distributor-ID": distributor_id } }
        );
        return jsonResult(data);
      }
    )
  );

  // --- Get Quote ---
  server.registerTool(
    "sophos_get_ba_quote",
    {
      title: "Get Sophos Business Automation Quote",
      description: `Get a distributor quote by proposal number.

Args:
  - distributor_id (string): Distributor ID (X-Distributor-ID).
  - proposal_number (string): Quote proposal number.`,
      inputSchema: {
        distributor_id: z.string().uuid().describe("Distributor ID"),
        proposal_number: z.string().describe("Quote proposal number"),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    withErrorHandling(async ({ distributor_id, proposal_number }) => {
      const data = await client.globalRequest<Record<string, unknown>>(
        `/business-automation/v1/quotes/${encodeURIComponent(proposal_number)}`,
        { headers: { "X-Distributor-ID": distributor_id } }
      );
      return jsonResult(data);
    })
  );

  // --- Get Partner Levels ---
  server.registerTool(
    "sophos_get_ba_partner_levels",
    {
      title: "Get Sophos Partner Levels",
      description: `Return partner program level info for partners in a billing sub-region.

Args:
  - distributor_id (string): Distributor ID (X-Distributor-ID).
  - billing_sub_region (string): Billing sub-region.
  - name (string, optional): Partner name filter.
  - edi_number (string, optional): Partner EDI account number.
  - updated_date (string, optional): Date the partner level was last updated.
  - limit (number, optional): Max results per page (default 50).
  - page (number, optional): Page number (default 1).`,
      inputSchema: {
        distributor_id: z.string().uuid().describe("Distributor ID"),
        billing_sub_region: z.string().describe("Billing sub-region"),
        name: z.string().optional().describe("Partner name filter"),
        edi_number: z.string().optional().describe("Partner EDI account number"),
        updated_date: z
          .string()
          .optional()
          .describe("Date the partner level was last updated"),
        limit: z
          .number()
          .int()
          .min(1)
          .max(100)
          .optional()
          .default(DEFAULT_PAGE_SIZE)
          .describe("Max results per page (default 50)"),
        page: z
          .number()
          .int()
          .min(1)
          .optional()
          .default(1)
          .describe("Page number (default 1)"),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    withErrorHandling(
      async ({ distributor_id, billing_sub_region, name, edi_number, updated_date, limit, page }) => {
        const params: Record<string, string> = {
          billingSubRegion: billing_sub_region,
          pageSize: String(limit),
          page: String(page),
        };
        if (name) params.name = name;
        if (edi_number) params.ediNumber = edi_number;
        if (updated_date) params.updatedDate = updated_date;

        const data = await client.globalRequest<Record<string, unknown>>(
          "/business-automation/v1/partners/level",
          { params, headers: { "X-Distributor-ID": distributor_id } }
        );
        return jsonResult(data);
      }
    )
  );

  // --- Get Pricing ---
  server.registerTool(
    "sophos_get_ba_pricing",
    {
      title: "Get Sophos Business Automation Pricing",
      description: `Return pricing info for a set of product lines for a reseller.

Args:
  - distributor_id (string): Distributor ID (X-Distributor-ID).
  - reseller_account_number (string): Reseller account number.
  - sector (string): "corporate", "education", or "government".
  - lines (array): Product lines. Each item: {product_name (required), quantity (required), term (required, months), line_id, discretionary_discount_percent, programme_discount ("dealReg" | "incumbent" | "teaming")}.
  - transaction_type (string, optional): "new" or "renew".
  - promo_codes (array, optional): Promo codes to apply.`,
      inputSchema: {
        distributor_id: z.string().uuid().describe("Distributor ID"),
        reseller_account_number: z.string().describe("Reseller account number"),
        sector: z
          .enum(["corporate", "education", "government"])
          .describe("Pricing sector"),
        lines: z
          .array(
            z.object({
              line_id: z.string().optional().describe("Caller-supplied line ID"),
              product_name: z.string().describe("Product name"),
              quantity: z.coerce.number().int().describe("Quantity"),
              term: z.coerce.number().int().describe("Term in months"),
              discretionary_discount_percent: z.coerce
                .number()
                .optional()
                .describe("Discretionary discount percent"),
              programme_discount: z
                .enum(["dealReg", "incumbent", "teaming"])
                .optional()
                .describe("Programme discount"),
            })
          )
          .min(1)
          .describe("Product lines to price (at least one)"),
        transaction_type: z
          .enum(["new", "renew"])
          .optional()
          .describe("Transaction type"),
        promo_codes: z
          .array(z.string())
          .optional()
          .describe("Promo codes to apply"),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    withErrorHandling(
      async ({
        distributor_id,
        reseller_account_number,
        sector,
        lines,
        transaction_type,
        promo_codes,
      }) => {
        const body: Record<string, unknown> = {
          resellerAccountNumber: reseller_account_number,
          sector,
          lines: lines.map((line) => {
            const item: Record<string, unknown> = {
              productName: line.product_name,
              quantity: line.quantity,
              term: line.term,
            };
            if (line.line_id) item.lineId = line.line_id;
            if (line.discretionary_discount_percent !== undefined)
              item.discretionaryDiscountPercent = line.discretionary_discount_percent;
            if (line.programme_discount) item.programmeDiscount = line.programme_discount;
            return item;
          }),
        };
        if (transaction_type) body.transactionType = transaction_type;
        if (promo_codes?.length) body.promoCodes = promo_codes;

        const data = await client.globalRequest<Record<string, unknown>>(
          "/business-automation/v1/pricing",
          { method: "POST", body, headers: { "X-Distributor-ID": distributor_id } }
        );
        return jsonResult(data);
      }
    )
  );
}
